stages:
  - build

variables:
  LC_ALL: 'en_US.UTF-8'
  LANG: 'en_US.UTF-8'
  GIT_STRATEGY: clone

build:
  stage: build
  tags:
    - app-deploy
  script:
    - yarn install
    - yarn build
    - cd ./ios
    - bundle install
    - bundle exec fastlane beta
  artifacts:
    paths:
      - ./ios/scoby.ipa
# stages:
#   - deployment

# variables:
#   LC_ALL: "en_US.UTF-8"
#   LANG: "en_US.UTF-8"
#   TOKEN: ${CI_PIPELINE_IID_TOKEN} # Past your Personal Access Token Here
#   GITLAB_URL: "https://gitlab.com"

# before_script:
#   - GITLAB_URL=$(echo ${CI_PROJECT_URL} |awk -F "/" '{print $1 "//" $2$3}')
#   - yarn install

# ios:upload_testflight:
#   dependencies: []
#   stage: deployment
#   variables:
#     VAR_NAME: BUILD_NUMBER_IOS # Counter of version Code IOS
#   script:
#     - 'VAR=$(curl -s -f  --header "PRIVATE-TOKEN: ${TOKEN}" "${GITLAB_URL}/api/v4/projects/${CI_PROJECT_ID}/variables/${VAR_NAME}" | jq  -r ''.value'' ) ' # Get from Personal Gitlab api the variable environement
#     - let VAR=VAR+1 # Increment the Version code
#     - export BUILD_NUMBER_IOS=${VAR} # Add it to your environement
#     - echo $BUILD_NUMBER_IOS # log
#     - yarn run postinstall
#     - cd ios
#     - bundle exec fastlane env
#     - fastlane beta # launch the lane beta
#     - 'curl -s -f --request PUT --header "PRIVATE-TOKEN: ${TOKEN}" "${GITLAB_URL}/api/v4/projects/${CI_PROJECT_ID}/variables/${VAR_NAME}" --form "value=${VAR}" '
#   tags:
#     - app-deploy # tag to launch your specific gitlab runner
#   when: manual

# # android:upload_internal:
# #   dependencies: []
# #   stage: deployment
# #   variables:
# #     VAR_NAME: BUILD_NUMBER_ANDROID # Counter of version Code Android
# #   script:
# #     - 'VAR=$(curl -s -f  --header "PRIVATE-TOKEN: ${TOKEN}" "${GITLAB_URL}/api/v4/projects/${CI_PROJECT_ID}/variables/${VAR_NAME}" | jq  -r ''.value'' ) ' # Get from Personal Gitlab api the variable environement
# #     - let VAR=VAR+1 # Increment the Version code
# #     - export BUILD_NUMBER_ANDROID=${VAR} # Add it to your environement
# #     - echo $BUILD_NUMBER_ANDROID # log
# #     - cd android
# #     - bundle exec fastlane env
# #     - fastlane upload_internal # launch the lane upload_internal
# #     - 'curl -s -f --request PUT --header "PRIVATE-TOKEN: ${TOKEN}" "${GITLAB_URL}/api/v4/projects/${CI_PROJECT_ID}/variables/${VAR_NAME}" --form "value=${VAR}" ' # save your Version Code in the CI
# #   tags:
# #     - android # tag to launch your specific gitlab runner
# #   when: manual
